set nocompatible
set backspace=indent,eol,start
set history=1000
set showcmd
set showmode
set gcr=a:blinkon0
set visualbell
set t_vb=
set autoread
set hidden
set timeoutlen=200
set ttimeoutlen=200

set encoding=utf-8

" Color
set t_Co=256
set background=dark
colorscheme default
syntax on
filetype plugin indent on

set incsearch
set hlsearch
set viminfo='100,f1

" Backup Files
set noswapfile
set nobackup
set nowb
silent !mkdir ~/.vim/backups > /dev/null 2>&1
set undodir=~/.vim/backups
set undofile

" Indentation
set autoindent
set smartindent
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab
set list listchars=tab:\ \ ,trail:·

set shortmess+=filmnrxoOtT
set ignorecase
set smartcase
set wildmenu
set wildmode=list:longest,full
set wildignore+=*/tmp/*,*.so,*.swp
set whichwrap=b,s,h,l,<,>,[,]
set scrolljump=2
set scrolloff=2
set foldenable
set foldmethod=syntax
set foldcolumn=3
"set foldlevelstart=1
set comments=sl:/*,mb:*,elx:*/  " auto format comment blocks
set cursorline
set winminheight=1
