#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#262626'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-e reload
hc keybind $Mod-Shift-c close_and_remove
hc keybind $Mod-Shift-Return spawn ${TERMINAL:-xfce4-terminal} # use your $TERMINAL with xterm as fallback
hc keybind $Mod-Escape spawn slock
hc keybind $Mod-s spawn rofi -show
hc keybind $Mod-w spawn rofi -show window
hc keybind $Mod-Shift-p emit_hook togglehidepanel

hc keybind $Mod-Shift-F7 chain , spawn ~/.screenlayout/work.sh , reload
hc keybind $Mod-F7 chain , spawn ~/.screenlayout/single.sh , reload

#hc keybind $Mod-e chain , lock , split bottom 0.5 , explode , focus -e down , spawn emacsclient -cn , unlock
hc keybind $Mod-e spawn emacsclient -cn

hc keybind $Mod-Shift-semicolon chain , lock , split right 0.5 , focus -e right , spawn ${TERMINAL:-xfce4-terminal} , unlock
hc keybind $Mod-semicolon chain , lock , split bottom 0.5 , explode , focus -e down , spawn ${TERMINAL:-xfce4-terminal} , unlock

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift_edge left
hc keybind $Mod-Shift-Down  shift_edge down
hc keybind $Mod-Shift-Up    shift_edge up
hc keybind $Mod-Shift-Right shift_edge right

hc keybind $Mod-Shift-h     or / shift left / chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
hc keybind $Mod-Shift-j     or / shift down / chain , lock , shift_to_monitor -d , focus_monitor -d , unlock
hc keybind $Mod-Shift-k     or / shift up / chain , lock , shift_to_monitor -u , focus_monitor -u , unlock
hc keybind $Mod-Shift-l     or / shift right / chain , lock , shift_to_monitor -r , focus_monitor -r , unlock

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       chain , split bottom 0.5 , focus -e down
hc keybind $Mod-o       chain , split right 0.5 , focus -e right
# let the current frame explode into subframes
hc keybind $Mod-x split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=("α" "β" "ξ" "δ" "ε" "φ" "γ")
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through available tags
hc keybind $Mod-bracketleft use_index -1 --skip-visible
hc keybind $Mod-bracketright  use_index +1 --skip-visible
# cycle through to next/prev tag
hc keybind $Mod-Control-Mod1-bracketleft use_index -1
hc keybind $Mod-Control-Mod1-bracketright  use_index +1
# move window to next/prev available tag
hc keybind $Mod-Shift-bracketleft move_index -1 --skip-visible
hc keybind $Mod-Shift-bracketright  move_index +1 --skip-visible

hc keybind $Mod-Tab use_previous

# layouting
hc keybind $Mod-c remove
hc keybind $Mod-f floating toggle
hc keybind $Mod-m fullscreen toggle
hc keybind $Mod-y pseudotile toggle

hc keybind $Mod-g set_layout grid
hc keybind $Mod-v set_layout horizontal # horizontal is vertical
hc keybind $Mod-z set_layout max

hc keybind $Mod-r rotate
hc keybind $Mod-Shift-r chain , lock , rotate , rotate , rotate , unlock
hc keybind $Mod-a chain , lock , rotate , rotate , unlock

hc keybind $Mod-period focus_monitor +1
hc keybind $Mod-comma focus_monitor -1

#hc keybind $Mod-t cycle_layout +1 vertical horizontal
hc keybind $Mod-t set_layout vertical

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-grave         cycle_all +1
hc keybind $Mod-Shift-grave   cycle_all -1

# next window in frame
hc keybind $Mod-n cycle +1
hc keybind $Mod-p cycle -1

hc keybind $Mod-i jumpto urgent

# cycle frames (branches)
hc keybind $Mod-b   cycle_frame +1
hc keybind $Mod-Shift-b   cycle_frame -1

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#262626'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#080808'
hc set frame_bg_active_color '#5f87af'
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 2
hc set frame_gap 50

#hc attr theme.active.color '#df5f00'
hc attr theme.active.color '#5f87af'
hc attr theme.normal.color '#262626'
hc attr theme.urgent.color '#df005f'
hc attr theme.inner_width 0
hc attr theme.outer_width 0
hc attr theme.inner_color white
hc attr theme.border_width 1
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#5f87af'
hc attr theme.active.outer_color '#262626'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

hc set focus_follows_mouse 1

hc set default_frame_layout 3
hc set default_direction_external_only 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' manage=on focus=on pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off focus=off
hc rule class='Conky' focus=off manage=on tag='γ' fullscreen=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# xfce4
# blueberry-tray
# blueberry-obex-agent.py
# xfce4-clipman
#dnfdragora-updater
# gnome-tweak-tool-lid-inhibitor
#imsettings-switch -n -q -x

#nm-applet &

# nvidia-settings -l

#xfce4-power-manager &

#start-pulseaudio-x11 &

#xfce4-panel --disable-wm-check --sm-client-disable &
#xscreensaver -no-splash &

#(emacsclient -cn || emacs -e "server-start") &
# xdg-user-dirs-update
# /usr/libexec/xfce-polkit
#xfsettingsd --replace --sm-client-disable

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

# find the panel
#panel=~/.config/herbstluftwm/panel.sh
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
#for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
#    # start it on each monitor
#    "$panel" $monitor &
#done

#polybar --reload laptop &
#polybar --reload main &
#polybar --reload left &
#polybar --reload right &

#for monitor in $(polybar --list-monitors | cut -d":" -f1) ; do
#    # start it on each monitor
#    MONITOR=$monitor polybar --reload top &
#done

compton &
source ~/.fehbg
