# If not running interactively, don't do anything
[[ "$-" != *i* ]] && return

# Make bash append rather than overwrite the history on disk
shopt -s histappend
shopt -s cdspell

[[ -f /etc/bash_completion ]] && . /etc/bash_completion

# Don't put duplicate lines in the history.
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
export HISTIGNORE=$'[ \t]*:&:[fb]g:exit:ls' # Ignore the ls command as well

# Whenever displaying the prompt, write the previous line to disk
export PROMPT_COMMAND="history -a"

# Alias
alias grep='grep --color'
alias df='df -h'
alias tree='tree -Ch'
alias ls='ls -h'
alias la='ls -a'
alias ll='ls -al'
alias vrc='vim ~/.vimrc'
alias c='clear'
alias g='git'
alias v="vagrant"
alias ll="ls -al"

# vi
export EDITOR='vim'
set -o vi

stty -ixon

export PS1=' '

# Path
export PATH=$PATH:/cygdrive/c/VirtualBox4/
export PATH=$PATH:/cygdrive/c/HashiCorp/Vagrant/bin
